### ISSUE TITLE
Link for the project website should be .io not .com

### ISSUE THREAD

**Issue by jacques** [greybax/awesome-IT-films#137]
Please use the following URL https://greybax.github.io/awesome-IT-films otherwise a 404 page is displayed:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2543/180644841-564570cb-1b1a-425a-b2fb-5641dfdfe714.png">

**Comment by jacques** [comment]
The project homepage link still takes you to a 404 page.  Click the cog to the right of the [code page](https://github.com/greybax/awesome-IT-films/) to update the link to the projects home page.

https://user-images.githubusercontent.com/2543/181189571-94d3969c-30dc-4050-b516-d4300da03d28.mov

**Comment by greybax** [comment]
@jacques thanks for the heads up 👍🏼 . I've updated this link as well

**Comment by jacques** [comment]
Thank you!
