### ISSUE TITLE
More useful badges?

### ISSUE THREAD

**Issue by greybax** [greybax/awesome-IT-films#24]
Big collection can be found here: https://shields.io
**P.S.** Please if you send PR just add link to this issue for relation.

**Comment by Prouser123** [comment]
What kind of thing are you looking for?

**Comment by greybax** [comment]
@Prouser123 This issue is more about improvisation. See PRs from another folks.

**Comment by perkinsjr** [comment]
@greybax in regards to Pull #28  we can use the storage.js and count the keys to return the amount of movies documentaties and tv-series for badging a simple solution. I can implement that at the same time.

**Comment by greybax** [comment]
Fixed with commit https://github.com/greybax/awesome-IT-films/commit/cffc650cd7f3c0a57d2881c2cc4a32f8c8e5ff4b
